name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
    inputs:
      config-path:
        required: true
        type: string
      NeedFoo:
        required: true
        type: boolean
        default: false
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/actions-test/.github/workflows/wf1.yml@v1
      with: 
        config-path: ${{ inputs.config-path }}

#     - uses: ./.github/workflows/wf1.yml
#       with: 
#         config-path: ${{ inputs.config-path }}
