name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
    inputs:
      config-path:
        required: true
        type: string
      NeedFoo:
        required: true
        type: boolean
        default: false
    
jobs:
  job1:
    if: ${{ inputs.NeedFoo }}
    uses: ./.github/workflows/wf1.yml
    with: 
      config-path: ${{ inputs.config-path }}
      
